# name: linux_amd64_arm64
# 
# on:
#   workflow_dispatch:
#     inputs:
#       binvern:
#         description: '指定Zig版本号(如0.15.2,不填则使用最新版本)'
#         required: false
#         type: string
#   schedule:
#     - cron: '0 2 * * *'  # 每天凌晨2点自动执行(使用最新版本)
#
# permissions:
#   contents: write
#
# jobs:
#   sync_binaries:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 拉取仓库代码
#         uses: actions/checkout@v4
#
#       - name: 下载Zig指定平台版本的二进制包
#         id: get_files
#         run: |
#           get_files_and_export_envs() {
#             URL="https://ziglang.org/download/index.json"
#             JSN="tmp.json" && [ ! -e ${JSN} ] && curl -fsLo ${JSN} ${URL}
#             TAG=${1}
#             if [ X0 != X${#TAG} ]; then
#               vnstr=$TAG
#             else
#               TAG='master' && vnstr=$(jq -r '.master.version' <${JSN})
#             fi
#             echo "使用的版本号: ${vnstr}" #&& rm -f ${JSN}
#             ##get pats-of-jq
#             set -- $(printf '."'${TAG}'"."%s-linux".tarball ' x86_64 aarch64)
#             set -- $(jq -r "${1}" <${JSN}) $(jq -r "${2}" <${JSN})
#             ##fetch-and-appendto-list
#             mkdir dist && xf= && for xf in $@; do
#               printf "\n#[TIP] Now downloading [${xf}]...\n"
#               curl -fLo dist/${xf##*/} ${xf}
#             done
#
#             ##追加到环境变量中
#             echo "VNSTR=${vnstr}" >>${GITHUB_ENV}
#             echo "BSURL=${URL%/index.json}" >>${GITHUB_ENV}
#           }
#           ##
#           get_files_and_export_envs ${{ github.event.inputs.binvern }}
#
#       - name: 发布到Releases
#         uses: softprops/action-gh-release@v2
#         with:
#           files: dist/*
#           tag_name: "v${{ env.VNSTR }}"  # 用版本号作为tag(如v0.12.0)
#           name: "Zig v${{ env.VNSTR }} Binaries"
#           body: |
#             自动同步自Zig官网的二进制程序
#             - 版本: ${{ env.VNSTR }}
#             - 官网下载地址: ${{ env.BSURL }}/${{ env.VNSTR }}
#           overwrite_files: false  # 不覆盖已有版本(避免重复发布同一版本)
